CREATE DATABASE healthcare_db;

CREATE TABLE healthcare (
name TEXT,
age INT,
gender TEXT,
blood_type TEXT,
medical_condition TEXT,
date_of_admission DATE,
doctor TEXT,
hospital TEXT,
insurance_provider TEXT,
billing_amount FLOAT,
room_number INT,
admission_type TEXT,
discharge_date DATE,
medication TEXT,
test_results TEXT
);

------------------------- 
-- Data Cleaning Queries
-------------------------

-- Counting Total Number Of Rows
SELECT COUNT(*) AS Total_Rows 
FROM healthcare ;

-- Find rows where doctor, hospital, or billing_amount has missing (NULL) values
SELECT *
FROM healthcare
WHERE doctor IS NULL
OR hospital IS NULL
OR billing_amount IS NULL;


-- Finding duplicate patient records based on name, age, doctor, and hospital
SELECT name, age, doctor, hospital, COUNT(*)
FROM healthcare
GROUP BY name, age, doctor, hospital
HAVING COUNT(*) > 1;

-- Geting all unique medical conditions 
SELECT DISTINCT medical_condition
FROM healthcare;

-- Count the number of records for each gender 
SELECT gender, COUNT(*)
FROM healthcare
GROUP BY gender;

-- Count the number of records for each admission type 
SELECT admission_type, COUNT(*)
FROM healthcare
GROUP BY admission_type;

-- Find the minimum and maximum billing amount 
SELECT 
ROUND(MIN(billing_amount)::numeric, 2) AS min_amount,
ROUND(MAX(billing_amount)::numeric, 2) AS max_amount
FROM healthcare;

-- Count the number of records for each test result
SELECT test_results, COUNT(*)
FROM healthcare
GROUP BY test_results;

-- Find the minimum, maximum, and average age of patients 
SELECT MIN(age) AS min_age, 
MAX(age) AS max_age, 
ROUND(AVG(age) :: numeric , 2) AS  avg_age
FROM healthcare;

-- Find the earliest and latest admission dates 
SELECT MIN(date_of_admission), MAX(date_of_admission)
FROM healthcare;

-----------------------------------
-- Patient Demographics Analysis 
-----------------------------------

-- Count the total number of patients
SELECT COUNT(*) AS total_patients
FROM healthcare;

-- Count the number of patients for each gender in the healthcare table
SELECT gender, COUNT(*) AS patient_count
FROM healthcare
GROUP BY gender;

-- Count the number of patients for each blood type 
SELECT blood_type, COUNT(*) AS patient_count
FROM healthcare
GROUP BY blood_type
ORDER BY patient_count DESC;

-- Categorize patients into age groups and count the number of patients in each group
SELECT 
CASE
WHEN age < 18 THEN 'Child'
WHEN age BETWEEN 18 AND 40 THEN 'Young Adult'
WHEN age BETWEEN 41 AND 60 THEN 'Adult'
ELSE 'Senior'
END AS age_group,
COUNT(*) AS patient_count
FROM healthcare
GROUP BY age_group
ORDER BY patient_count DESC;

-- Rank patients based on billing amount to identify high-value patients
SELECT 
name,
gender,
billing_amount,
RANK() OVER (ORDER BY billing_amount DESC) AS billing_rank
FROM healthcare;

----------------------------------
-- Hospital Performance Analysis 
----------------------------------

-- Count the total number of patients in each hospital 
SELECT hospital, COUNT(*) AS total_patients
FROM healthcare
GROUP BY hospital
ORDER BY total_patients DESC;

-- Calculate total revenue generated by each hospital
SELECT hospital, ROUND(SUM(billing_amount)::numeric , 2) AS total_revenue
FROM healthcare
GROUP BY hospital;

-- Find the hospital with the highest total revenue from billing_amount
SELECT hospital, ROUND(SUM(billing_amount):: numeric,2) AS total_revenue
FROM healthcare
GROUP BY hospital
ORDER BY total_revenue DESC
LIMIT 1;

-- Calculate the average billing amount for each hospital
SELECT hospital, AVG(billing_amount) AS avg_billing
FROM healthcare
GROUP BY hospital
ORDER BY avg_billing DESC;

-- Find top 3 hospitals based on total revenue generated
SELECT *
FROM (
SELECT hospital,
SUM(billing_amount) AS total_revenue,
RANK() OVER (ORDER BY SUM(billing_amount) DESC) AS rank
FROM healthcare
GROUP BY hospital
) t
WHERE rank <= 3;

-- Calculate revenue contribution percentage of each hospital
SELECT 
hospital,
SUM(billing_amount) AS revenue,
ROUND(
(SUM(billing_amount) * 100.0 / 
(SELECT SUM(billing_amount) FROM healthcare))::NUMERIC,
2
) AS revenue_percentage
FROM healthcare
GROUP BY hospital
order by revenue_percentage desc;


----------------------------------
-- Doctor Performance Analysis 
----------------------------------

-- Count the number of patients handled by each doctor 
SELECT doctor, COUNT(*) AS patient_count
FROM healthcare
GROUP BY doctor
ORDER BY patient_count DESC;

-- Find the doctor with the highest number of patients
SELECT doctor, COUNT(*) AS patient_count
FROM healthcare
GROUP BY doctor
ORDER BY patient_count DESC
LIMIT 1;

-- Calculate the average billing amount for each doctor
SELECT doctor ,ROUND(AVG(billing_amount):: numeric,2) AS avg_billing
FROM healthcare
GROUP BY doctor
ORDER BY avg_billing DESC;

------------------------------
-- Medical Condition Analysis 
------------------------------

-- Count the number of patients for each medical condition
SELECT medical_condition, COUNT(*) AS patient_count
FROM healthcare
GROUP BY medical_condition
ORDER BY patient_count DESC;

-- Calculate the average billing amount for each medical condition 
SELECT medical_condition, ROUND(AVG(billing_amount):: NUMERIC,2) AS avg_billing
FROM healthcare
GROUP BY medical_condition
ORDER BY avg_billing DESC;

-- Find the medical condition that generated the highest total billing amount
SELECT medical_condition, SUM(billing_amount) AS total_billing
FROM healthcare
GROUP BY medical_condition
ORDER BY total_billing DESC
LIMIT 1;

-- Identify most common disease in each hospital
SELECT *
FROM (
SELECT hospital,
medical_condition,
COUNT(*) AS patient_count,
RANK() OVER (PARTITION BY hospital ORDER BY COUNT(*) DESC) AS rank
FROM healthcare
GROUP BY hospital, medical_condition
) t
WHERE rank = 1;

-----------------------------
--Admission Trend Analysis
-----------------------------

-- Count the number of patients admitted each month
SELECT DATE_TRUNC('month', date_of_admission) AS month,
COUNT(*) AS patient_count
FROM healthcare
GROUP BY month
ORDER BY month;

-- Count the number of patients admitted each year 
SELECT DATE_TRUNC('year', date_of_admission) AS year,
COUNT(*) AS patient_count
FROM healthcare
GROUP BY year
ORDER BY year;

-- Calculate total revenue generated from each admission type
SELECT admission_type,
ROUND(SUM(billing_amount):: NUMERIC,2) AS total_revenue
FROM healthcare
GROUP BY admission_type
ORDER BY total_revenue DESC;

-- Analyze month-on-month patient growth using LAG function
SELECT 
DATE_TRUNC('month', date_of_admission) AS month,
COUNT(*) AS total_patients,
LAG(COUNT(*)) OVER (ORDER BY DATE_TRUNC('month', date_of_admission)) AS prev_month,
COUNT(*) - LAG(COUNT(*)) OVER (ORDER BY DATE_TRUNC('month', date_of_admission)) AS growth
FROM healthcare
GROUP BY month
ORDER BY month desc;

-- Calculate running total of revenue over time
SELECT 
date_of_admission,
SUM(billing_amount) OVER (ORDER BY date_of_admission) AS running_revenue
FROM healthcare;

-----------------------------
-- Stay Duration Analysis 
-----------------------------

-- Calculate hospital stay duration for each patient
SELECT 
name,
date_of_admission,
discharge_date,
(discharge_date - date_of_admission) AS stay_days
FROM healthcare;

-- Calculate the average hospital stay (in days) for all patients
SELECT 
ROUND(AVG(discharge_date - date_of_admission), 2) AS avg_stay_days
FROM healthcare;

-- Classify patients based on length of hospital stay
SELECT 
name,
hospital,
(discharge_date - date_of_admission) AS stay_days,
CASE
WHEN (discharge_date - date_of_admission) > 10 THEN 'Long Stay'
ELSE 'Normal Stay'
END AS stay_type
FROM healthcare;

-- Identify patients with multiple hospital visits (readmission cases)
SELECT 
name,
COUNT(*) AS visit_count
FROM healthcare
GROUP BY name
HAVING COUNT(*) > 1;

---------------------------------
-- Billing & Insurance Analysis 
---------------------------------

-- Calculate total billing amount for each insurance provider
SELECT insurance_provider, SUM(billing_amount) AS total_billing
FROM healthcare
GROUP BY insurance_provider
ORDER BY total_billing DESC;

-- Count the number of patients for each insurance provider 
SELECT insurance_provider, COUNT(*) AS patient_count
FROM healthcare
GROUP BY insurance_provider
ORDER BY patient_count DESC;

-- Calculate the average billing amount for each insurance provider 
SELECT insurance_provider, ROUND(AVG(billing_amount):: NUMERIC ,2) AS avg_billing
FROM healthcare
GROUP BY insurance_provider
ORDER BY avg_billing DESC;

-- Show top 5 patients with the highest billing amount
SELECT name, hospital, billing_amount
FROM healthcare
ORDER BY billing_amount DESC
LIMIT 5;

-- Calculate the average billing amount for each gender
SELECT gender,
ROUND(AVG(billing_amount)::numeric, 2) AS avg_billing
FROM healthcare
GROUP BY gender;

-- Identify patients whose billing is above average
SELECT name, billing_amount
FROM healthcare
WHERE billing_amount > (
SELECT AVG(billing_amount) FROM healthcare
);

-- Analyze insurance providers based on cost efficiency and patient coverage
SELECT 
insurance_provider,
COUNT(*) AS total_patients,
ROUND(AVG(billing_amount)::numeric ,2) AS avg_cost,
ROUND(AVG(discharge_date - date_of_admission)::numeric,2) AS avg_stay
FROM healthcare
GROUP BY insurance_provider;
